# Move this file to the top of the repository source tree
# (so it is in the same directory as the 'platformio.ini' file.

[platformio]
default_envs = esp32dev

[env:esp32dev]
board = esp32dev
platform = ${esp32.platform}
platform_packages = ${esp32.platform_packages}
#custom_usermods = audioreactive
custom_usermods = alt_word_clock
build_unflags = ${common.build_unflags}
lib_deps = ${esp32.lib_deps}
monitor_filters = esp32_exception_decoder
board_build.partitions = ${esp32.default_partitions}
build_flags = ${common.build_flags} ${esp32.build_flags} -D WLED_RELEASE_NAME=\"ESP32\" #-D WLED_DISABLE_BROWNOUT_DET
